development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: <%= ENV['REDIS_URL'] %>
  url: redis://redistogo:baa6da097a7bb4707c5cea5314c98d88@pike.redistogo.com:11399/
  channel_prefix: Lax_production
